const express = require('express');

const app = express();
app.use(express.json());
const port = 8080;

const firebase = require('./firebase');
const local = require('./data/db');
const fs = require('fs');

// on server start, populate data.js from persistent data.json
local.loadData();


//* ROUTES
//TODO: plan out all required routes

//? get user with id 'uid'
app.get("/user/:uid", (req, res) => {
    if (!req.params.uid) {
        res.status(400);
        res.send("Error: Missing parameter 'uid'");
    }
    else if (!local.users[req.params.uid]) {
        res.status(404);
        res.send("Error: User not found");
    }
    else {
        res.json(local.users[req.params.uid]);
    }
});

//? add new user with id generated by firebase auth
app.post("/add-user", (req, res) => {
    const body = req.body;
    if (!body.id) {
        res.status(400);
        res.send("Error: incorrect parameters for add-user");
    }
    else if (local.users[body.id] !== undefined) {
        res.status(409);
        res.send("Error: uid taken");
    }
    else {
        //TODO: firebase auth
        local.users[body.id] = {
            id: body.id,
            posts: [],
            saved: [],
        }
        local.writeUsers();
        res.send("User was added");
    }
});

app.listen(port);

console.log(`listening on http://localhost:${port}/`);
console.log("Press Ctrl-C to quit");

// // // //   //
//* TESTING  *//
// // // //   //
const axios = require('axios');

axios.get("http://localhost:8080/user/user1")
    .then(res => {
        console.log(res.data);
    }, res => {
        console.log(res.response.data);
    });

// axios.post("http://localhost:8080/add-user", {
//     id: "einar",
// })

axios.get("http://localhost:8080/user/einar")
    .then(res => {
        console.log(res.data);
    });